// Project 2 MIU 1208
// Jacob Figueroa

var json = {
	"entry 1": {
		"entries": ["Wish List Item: ", "Album: 2205 (2010/2011)"],
		"quantity": ["Number of Items I would like: ", "2"],
		"firstname": ["First Name: ", "Jacob"],
		"lastname": ["Last Name: ", "Figueroa"],
		"username": ["Username: ", "jacobfigueroa"],
		"password": ["Password: ", "Zander11"],
		"confirmpw": ["Password Confirmed: ", "Zander11"],
		"email": ["Email: ", "zandermpls@fullsail.edu"],
		"mydate": ["Date: ", "08/21/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "I think Norell will like this album."]
	},
	"entry 2": {
		"entries": ["Wish List Item: ", "Album: Sick of Sarah (2008)"],
		"quantity": ["Number of Items I would like: ", "3"],
		"firstname": ["First Name: ", "Mary"],
		"lastname": ["Last Name: ", "Norell"],
		"username": ["Username: ", "marynorell"],
		"password": ["Password: ", "Norell22"],
		"confirmpw": ["Password Confirmed: ", "Norell22"],
		"email": ["Email: ", "norell@her.com"],
		"mydate": ["Date: ", "09/25/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "This is for my friend Angelica!"]
	},
	"entry 3": {
		"entries": ["Wish List Item: ", "Autographed Print: SOS Live"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Johnny"],
		"lastname": ["Last Name: ", "Jiron"],
		"username": ["Username: ", "tponch"],
		"password": ["Password: ", "Taco86"],
		"confirmpw": ["Password Confirmed: ", "Taco86"],
		"email": ["Email: ", "tponch@me.com"],
		"mydate": ["Date: ", "07/31/12"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "Priscilla will like this."]
	},
	"entry 4": {
		"entries": ["Wish List Item: ", "Autographed Print: SOS In Studio"],
		"quantity": ["Number of Items I would like: ", "2"],
		"firstname": ["First Name: ", "Caleb"],
		"lastname": ["Last Name: ", "Figueroa"],
		"username": ["Username: ", "guitarman"],
		"password": ["Password: ", "Lovemus1c"],
		"confirmpw": ["Password Confirmed: ", "Lovemus1c"],
		"email": ["Email: ", "rockstar@him.biz"],
		"mydate": ["Date: ", "08/25/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "Girlfriend loves this band."]
	},
	"entry 5": {
		"entries": ["Wish List Item: ", "Sick of Sarah V-Neck T-Shirt"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Priscilla"],
		"lastname": ["Last Name: ", "Rodriguez"],
		"username": ["Username: ", "brokepretty"],
		"password": ["Password: ", "Work1n"],
		"confirmpw": ["Password Confirmed: ", "Work1n"],
		"email": ["Email: ", "brokeandpretty@me.com"],
		"mydate": ["Date: ", "09/01/12"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "Can't wait to wear this!"]
	},
	"entry 6": {
		"entries": ["Wish List Item: ", "Tank Top Muscle Tee"],
		"quantity": ["Number of Items I would like: ", "2"],
		"firstname": ["First Name: ", "Angelica"],
		"lastname": ["Last Name: ", "Ramirez"],
		"username": ["Username: ", "angelicar"],
		"password": ["Password: ", "Equality1"],
		"confirmpw": ["Password Confirmed: ", "Equality1"],
		"email": ["Email: ", "aramirez@her.com"],
		"mydate": ["Date: ", "08/15/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "This will look cute on Norell"]
	},
	"entry 7": {
		"entries": ["Wish List Item: ", "Long Key Necklace"],
		"quantity": ["Number of Items I would like: ", "5"],
		"firstname": ["First Name: ", "Lo"],
		"lastname": ["Last Name: ", "Beth"],
		"username": ["Username: ", "lobethj"],
		"password": ["Password: ", "Bones26"],
		"confirmpw": ["Password Confirmed: ", "Bones26"],
		"email": ["Email: ", "likekeys@me.com"],
		"mydate": ["Date: ", "07/29/12"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "Going to mod these for some body chains."]
	},
	"entry 8": {
		"entries": ["Wish List Item: ", "Key Necklace Choker"],
		"quantity": ["Number of Items I would like: ", "4"],
		"firstname": ["First Name: ", "Emily"],
		"lastname": ["Last Name: ", "Pufall"],
		"username": ["Username: ", "fullheart"],
		"password": ["Password: ", "Lovew1ns"],
		"confirmpw": ["Password Confirmed: ", "Lovew1ns"],
		"email": ["Email: ", "heart@her.com"],
		"mydate": ["Date: ", "09/10/2012"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "I will wear this to the show!"]
	},
	"entry 9": {
		"entries": ["Wish List Item: ", "Album: Sick of Sarah (2008)"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Andra"],
		"lastname": ["Last Name: ", "Larae"],
		"username": ["Username: ", "sciencewins"],
		"password": ["Password: ", "Lovesc1ence"],
		"confirmpw": ["Password Confirmed: ", "Lovesc1ence"],
		"email": ["Email: ", "rock@theearth.com"],
		"mydate": ["Date: ", "09/30/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "My cousin loves this band!"]
	},
	"entry 10": {
		"entries": ["Wish List Item: ", "Sick of Sarah V-Neck T-Shirt"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Grant"],
		"lastname": ["Last Name: ", "Mayland"],
		"username": ["Username: ", "nightstalker"],
		"password": ["Password: ", "DJN1ght"],
		"confirmpw": ["Password Confirmed: ", "DJN1ght"],
		"email": ["Email: ", "nightstalker@dj.com"],
		"mydate": ["Date: ", "09/15/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "This will look cute on my girlfriend!"]
	},
	"entry 11": {
		"entries": ["Wish List Item: ", "Key Necklace Choker"],
		"quantity": ["Number of Items I would like: ", "2"],
		"firstname": ["First Name: ", "Gisselle"],
		"lastname": ["Last Name: ", "Vallejos"],
		"username": ["Username: ", "gyspyheart"],
		"password": ["Password: ", "C1tarre"],
		"confirmpw": ["Password Confirmed: ", "C1tarre"],
		"email": ["Email: ", "beachgirl@me.com"],
		"mydate": ["Date: ", "09/19/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "One is for me, one is for my sister."]
	},
	"entry 12": {
		"entries": ["Wish List Item: ", "Tank Top Muscle Tee"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Wendy"],
		"lastname": ["Last Name: ", "Thorpe"],
		"username": ["Username: ", "clearing"],
		"password": ["Password: ", "HealEarth1"],
		"confirmpw": ["Password Confirmed: ", "HealEarth1"],
		"email": ["Email: ", "clearing@earth.com"],
		"mydate": ["Date: ", "10/01/2012"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "Thought I would get a new shirt to lounge around in."]
	},
	"entry 13": {
		"entries": ["Wish List Item: ", "Long Key Necklace"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Elliott"],
		"lastname": ["Last Name: ", "Roche"],
		"username": ["Username: ", "costello"],
		"password": ["Password: ", "mus1c1aN"],
		"confirmpw": ["Password Confirmed: ", "mus1c1aN"],
		"email": ["Email: ", "justplay@guitar.com"],
		"mydate": ["Date: ", "09/11/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "I think my girlfriend will love this."]
	},
	"entry 14": {
		"entries": ["Wish List Item: ", "Autographed Print: SOS Live"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Adrian"],
		"lastname": ["Last Name: ", "Kerstin"],
		"username": ["Username: ", "cleanwater"],
		"password": ["Password: ", "forEvery1"],
		"confirmpw": ["Password Confirmed: ", "forEvery1"],
		"email": ["Email: ", "cleanwater@bio.com"],
		"mydate": ["Date: ", "09/17/2012"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "These girls are cute AND they rock!"]
	},
	"entry 15": {
		"entries": ["Wish List Item: ", "Autographed Print: SOS In Studio"],
		"quantity": ["Number of Items I would like: ", "2"],
		"firstname": ["First Name: ", "John"],
		"lastname": ["Last Name: ", "Smith"],
		"username": ["Username: ", "sosrocks"],
		"password": ["Password: ", "rockMus1c"],
		"confirmpw": ["Password Confirmed: ", "rockMus1c"],
		"email": ["Email: ", "lovesos@smith.biz"],
		"mydate": ["Date: ", "09/27/2012"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "One for my brother, one for me. They're awesome!"]
	},
	"entry 16": {
		"entries": ["Wish List Item: ", "Album: 2205 (2010/2011)"],
		"quantity": ["Number of Items I would like: ", "2"],
		"firstname": ["First Name: ", "Michael"],
		"lastname": ["Last Name: ", "McManus"],
		"username": ["Username: ", "greathair"],
		"password": ["Password: ", "Sc1ssors"],
		"confirmpw": ["Password Confirmed: ", "Sc1ssors"],
		"email": ["Email: ", "levante@hair.com"],
		"mydate": ["Date: ", "10/15/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "My friend wants this album."]
	},
	"entry 17": {
		"entries": ["Wish List Item: ", "Long Key Necklace"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Kari"],
		"lastname": ["Last Name: ", "Tribble"],
		"username": ["Username: ", "allareone"],
		"password": ["Password: ", "oneL0ve"],
		"confirmpw": ["Password Confirmed: ", "oneL0ve"],
		"email": ["Email: ", "clearnow@awake.com"],
		"mydate": ["Date: ", "09/28/2012"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "Love the necklace!"]
	},
	"entry 18": {
		"entries": ["Wish List Item: ", "Autographed Print: SOS In Studio"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Richard"],
		"lastname": ["Last Name: ", "Simons"],
		"username": ["Username: ", "punkrock1"],
		"password": ["Password: ", "sos4Eva"],
		"confirmpw": ["Password Confirmed: ", "sos4Eva"],
		"email": ["Email: ", "longliverockn@roll.com"],
		"mydate": ["Date: ", "09/25/2012"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "Going to hang this up by the stereo."]
	},
	"entry 19": {
		"entries": ["Wish List Item: ", "Album: Sick of Sarah (2008)"],
		"quantity": ["Number of Items I would like: ", "1"],
		"firstname": ["First Name: ", "Phaedra"],
		"lastname": ["Last Name: ", "Williams"],
		"username": ["Username: ", "sosweet"],
		"password": ["Password: ", "V1olingrl"],
		"confirmpw": ["Password Confirmed: ", "V1olingrl"],
		"email": ["Email: ", "playstrings@violin.com"],
		"mydate": ["Date: ", "10/03/2012"],
		"slider": ["Gift for a Friend? ", "No"],
		"comments": ["Comments: ", "Can't get their songs out of my head!"]
	},
	"entry 20": {
		"entries": ["Wish List Item: ", "Key Necklace Choker"],
		"quantity": ["Number of Items I would like: ", "3"],
		"firstname": ["First Name: ", "Justina"],
		"lastname": ["Last Name: ", "Flones"],
		"username": ["Username: ", "lovemytwins"],
		"password": ["Password: ", "Nostress4"],
		"confirmpw": ["Password Confirmed: ", "Nostress4"],
		"email": ["Email: ", "stresskills@nomore.com"],
		"mydate": ["Date: ", "09/10/2012"],
		"slider": ["Gift for a Friend? ", "Yes"],
		"comments": ["Comments: ", "Getting these for my best friends."]
	}
	
}
